# Generated by Django 2.1.2 on 2018-11-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('img_1', models.CharField(max_length=1000)),
                ('img_2', models.CharField(max_length=1000)),
                ('body_1', models.CharField(max_length=250)),
                ('body_2', models.CharField(max_length=800)),
                ('body_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Short_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.Posts')),
            ],
        ),
    ]
