# Generated by Django 2.1.2 on 2019-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_m', models.CharField(max_length=200)),
                ('good_choices', models.PositiveIntegerField(default=0)),
                ('choices', models.CharField(blank=True, max_length=2000, null=True)),
                ('bad_choices', models.PositiveIntegerField(default=0)),
                ('activity', models.BooleanField(default=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(max_length=7)),
                ('q1', models.CharField(max_length=3)),
                ('q2', models.CharField(max_length=3)),
                ('made', models.DateTimeField(auto_now=True)),
                ('something', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Leftovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Leftovers', max_length=10)),
                ('good_choices', models.PositiveIntegerField(default=0)),
                ('neutral_choices', models.PositiveIntegerField(default=0)),
                ('bad_choices', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
