# Generated by Django 2.1.2 on 2019-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='time_stamps',
            field=models.TextField(blank=True),
        ),
    ]
