# Generated by Django 2.1.2 on 2019-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0003_auto_20190120_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='made',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
