# Generated by Django 2.1.2 on 2019-01-22 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0004_auto_20190122_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='made',
        ),
        migrations.AddField(
            model_name='id',
            name='time_stamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), blank=True, null=True, size=None),
        ),
    ]
