# Generated by Django 2.1.2 on 2019-01-22 13:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0005_auto_20190122_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='time_stamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), blank=True, default=list, null=True, size=None),
        ),
    ]
