# Generated by Django 2.1.2 on 2018-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0004_auto_20181208_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftovers',
            name='bad_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='good_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='neutral_choices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
