# Generated by Django 2.1.2 on 2018-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0006_auto_20181209_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='gender',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='id',
            name='q1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='id',
            name='q2',
            field=models.CharField(max_length=3),
        ),
    ]
