# Generated by Django 2.1.5 on 2019-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0014_auto_20190119_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='choices',
            field=models.TextField(default=''),
        ),
    ]
