# Generated by Django 2.1.2 on 2018-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0002_auto_20181208_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftovers',
            name='name',
            field=models.CharField(default='Leftovers', max_length=10),
        ),
    ]
