# Generated by Django 2.1.2 on 2018-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0003_leftovers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='bad_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='id',
            name='good_choices',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='id',
            name='neutral_choices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
