# Generated by Django 2.1.2 on 2018-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_m', models.CharField(max_length=200)),
                ('good_choices', models.CharField(max_length=50)),
                ('neutral_choices', models.CharField(max_length=50)),
                ('bad_choices', models.CharField(max_length=50)),
            ],
        ),
    ]
